services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: ./backend
    container_name: backend
    command: ["python", "api_server.py"]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  consumer:
    build: ./backend
    container_name: consumer
    command: ["python", "consumer.py"]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
